<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>OnlyWar</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../OnlyWar.Domain/OnlyWar.Domain.csproj" />
    <ProjectReference Include="../OnlyWar.Abstractions/OnlyWar.Abstractions.csproj" />
    <ProjectReference Include="../OnlyWar.Operations.Abstractions/OnlyWar.Operations.Abstractions.csproj" />
    <ProjectReference Include="../OnlyWar.Battles.Abstractions/OnlyWar.Battles.Abstractions.csproj" />
    <ProjectReference Include="../OnlyWar.Medical.Abstractions/OnlyWar.Medical.Abstractions.csproj" />
    <ProjectReference Include="../OnlyWar.Runtime/OnlyWar.Runtime.csproj" />
    <Using Include="OnlyWar.Abstractions" />
    <Using Include="OnlyWar.Medical.Abstractions" />
    <Using Include="OnlyWar.Domain.Missions" />
    <Using Include="OnlyWar.Domain.Extensions" />
    <Using Include="OnlyWar.Domain.Intelligence" />
    <Using Include="OnlyWar.Domain.Math" />
    <Using Include="OnlyWar.Operations.Abstractions" />
    <Using Include="OnlyWar.Operations.Extensions" />
    <Using Include="OnlyWar.Operations.Fleets" />
    <Using Include="OnlyWar.Operations.Intelligence" />
    <Using Include="OnlyWar.Operations.Missions" />
    <Using Include="OnlyWar.Operations.Missions.Recon" />
    <Using Include="OnlyWar.Operations.Personnel" />
    <Using Include="OnlyWar.Operations.Readiness" />
    <Using Include="OnlyWar.Operations.Recruitment" />
    <Using Include="OnlyWar.Runtime.Factories" />
    <Using Include="OnlyWar.Runtime.Logging" />
    <InternalsVisibleTo Include="OnlyWar.Tests" />
  </ItemGroup>
</Project>
