using OnlyWar.Helpers.Simulation;
using OnlyWar.Models;
using OnlyWar.Models.Orders;
using OnlyWar.Models.Planets;
using System;
using System.Collections.Generic;
using System.Linq;

namespace OnlyWar.Helpers.Turns
{
    /// <summary>
    /// Adds the orders generated by non-player strategy to a turn's order stream.
    /// Mission shaping remains a separate phase so its effects are already present
    /// when this planner evaluates threats.
    /// </summary>
    internal sealed class TurnOrderPlanner
    {
        private readonly GameSession _session;
        private readonly FactionStrategyController _strategyController;

        internal TurnOrderPlanner(
            GameSession session,
            FactionStrategyController strategyController)
        {
            _session = session ?? throw new ArgumentNullException(nameof(session));
            _strategyController = strategyController;
        }

        internal void AppendNpcOrders(List<Order> orders, Sector sector, Planet planet = null)
        {
            GameRulesData rules = _session.Rules;
            IEnumerable<Faction> enemyFactions = rules.Factions
                .Where(faction => !faction.IsPlayerFaction && !faction.IsDefaultFaction);

            foreach (Faction faction in enemyFactions)
            {
                orders.AddRange(planet == null
                    ? _strategyController.GenerateFactionOrders(faction, sector)
                    : _strategyController.GenerateFactionOrders(faction, sector, planet));
            }

            Faction defaultFaction = rules.DefaultFaction;
            if (defaultFaction == null)
            {
                return;
            }

            orders.AddRange(planet == null
                ? _strategyController.GenerateFactionOrders(defaultFaction, sector, defensiveOnly: true)
                : _strategyController.GenerateFactionOrders(defaultFaction, sector, planet, defensiveOnly: true));
        }
    }
}
