<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>OnlyWar</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../OnlyWar.Domain/OnlyWar.Domain.csproj" />
    <ProjectReference Include="../OnlyWar.Abstractions/OnlyWar.Abstractions.csproj" />
    <ProjectReference Include="../OnlyWar.Persistence.Abstractions/OnlyWar.Persistence.Abstractions.csproj" />
    <InternalsVisibleTo Include="OnlyWar.Tests" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.0" />
  </ItemGroup>
</Project>
