<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>OnlyWar</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../OnlyWar.Domain/OnlyWar.Domain.csproj" />
    <ProjectReference Include="../OnlyWar.Abstractions/OnlyWar.Abstractions.csproj" />
    <ProjectReference Include="../OnlyWar.Runtime.Abstractions/OnlyWar.Runtime.Abstractions.csproj" />
    <Using Include="OnlyWar.Abstractions" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Models/Soldiers/Names/given_names.txt" LogicalName="OnlyWar.SoldierNames.Given" />
    <EmbeddedResource Include="Models/Soldiers/Names/surnames.txt" LogicalName="OnlyWar.SoldierNames.Surnames" />
  </ItemGroup>
</Project>
