<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>OnlyWar</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../OnlyWar.Domain/OnlyWar.Domain.csproj" />
    <ProjectReference Include="../OnlyWar.Abstractions/OnlyWar.Abstractions.csproj" />
    <ProjectReference Include="../OnlyWar.Generation.Abstractions/OnlyWar.Generation.Abstractions.csproj" />
    <ProjectReference Include="../OnlyWar.Runtime/OnlyWar.Runtime.csproj" />
    <Using Include="OnlyWar.Abstractions" />
    <Using Include="OnlyWar.Generation.Abstractions" />
    <Using Include="OnlyWar.Domain.Formatting" />
    <Using Include="OnlyWar.Domain.Intelligence" />
    <Using Include="OnlyWar.Domain.Simulation" />
    <Using Include="OnlyWar.Generation.Chapter" />
    <Using Include="OnlyWar.Generation.Scenarios" />
    <Using Include="OnlyWar.Generation.World" />
    <Using Include="OnlyWar.Runtime.Random" />
    <InternalsVisibleTo Include="OnlyWar.Tests" />
  </ItemGroup>
</Project>
