using OnlyWar.Campaign.Simulation;
using OnlyWar.Domain;
using OnlyWar.Domain.Orders;
using OnlyWar.Domain.Planets;
using System;
using System.Collections.Generic;
using System.Linq;

namespace OnlyWar.Campaign.Turns
{
    /// <summary>
    /// Adds the orders generated by non-player strategy to a turn's order stream.
    /// Mission shaping remains a separate phase so its effects are already present
    /// when this planner evaluates threats.
    /// </summary>
    internal sealed class TurnOrderPlanner
    {
        private readonly CampaignTurnContext _turn;
        private readonly FactionStrategyController _strategyController;

        internal TurnOrderPlanner(
            ICampaignSimulationSession session,
            FactionStrategyController strategyController)
            : this(CampaignTurnContext.From(session), strategyController)
        {
        }

        internal TurnOrderPlanner(
            CampaignTurnContext turn,
            FactionStrategyController strategyController)
        {
            _turn = turn ?? throw new ArgumentNullException(nameof(turn));
            _strategyController = strategyController;
        }

        internal void AppendNpcOrders(List<Order> orders, Sector sector, Planet planet = null)
        {
            GameRulesData rules = _turn.Rules;
            IEnumerable<Faction> enemyFactions = rules.Factions
                .Where(faction => !FactionRelationshipService.IsImperial(faction));

            foreach (Faction faction in enemyFactions)
            {
                List<Order> factionOrders = (planet == null
                    ? _strategyController.GenerateFactionOrders(faction, sector)
                    : _strategyController.GenerateFactionOrders(faction, sector, planet)).ToList();
                orders.AddRange(factionOrders);
            }

            Faction defaultFaction = rules.DefaultFaction;
            if (defaultFaction == null)
            {
                return;
            }

            orders.AddRange(planet == null
                ? _strategyController.GenerateFactionOrders(defaultFaction, sector, defensiveOnly: true)
                : _strategyController.GenerateFactionOrders(defaultFaction, sector, planet, defensiveOnly: true));

            // Attach after every faction has planned. This lets a strategic invasion force see an assault generated
            // by a later NPC faction and reserve its Warboss for the defensive battle, preserving
            // the one-battle-per-turn command rule regardless of faction ordering in the rules DB.
            foreach (Faction faction in FactionCapabilities.WithCapability(
                rules.Factions, FactionBehavior.GeneratesInvasions))
            {
                FactionCapabilityCampaignProcessor.AttachCommandersToTacticalOrders(
                    sector, faction, orders, orders);
            }
        }
    }
}

