<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>OnlyWar</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../OnlyWar.Domain/OnlyWar.Domain.csproj" />
    <ProjectReference Include="../OnlyWar.Abstractions/OnlyWar.Abstractions.csproj" />
    <ProjectReference Include="../OnlyWar.Application.Abstractions/OnlyWar.Application.Abstractions.csproj" />
    <ProjectReference Include="../OnlyWar.Generation.Abstractions/OnlyWar.Generation.Abstractions.csproj" />
    <ProjectReference Include="../OnlyWar.Operations.Abstractions/OnlyWar.Operations.Abstractions.csproj" />
    <ProjectReference Include="../OnlyWar.Persistence.Abstractions/OnlyWar.Persistence.Abstractions.csproj" />
    <ProjectReference Include="../OnlyWar.Runtime.Abstractions/OnlyWar.Runtime.Abstractions.csproj" />
    <ProjectReference Include="../OnlyWar.Battles.Abstractions/OnlyWar.Battles.Abstractions.csproj" />
    <ProjectReference Include="../OnlyWar.Medical.Abstractions/OnlyWar.Medical.Abstractions.csproj" />
    <ProjectReference Include="../OnlyWar.Runtime/OnlyWar.Runtime.csproj" />
    <ProjectReference Include="../OnlyWar.Campaign/OnlyWar.Campaign.csproj" />
    <ProjectReference Include="../OnlyWar.Battles/OnlyWar.Battles.csproj" />
    <ProjectReference Include="../OnlyWar.Medical/OnlyWar.Medical.csproj" />
    <ProjectReference Include="../OnlyWar.Operations/OnlyWar.Operations.csproj" />
    <ProjectReference Include="../OnlyWar.Persistence/OnlyWar.Persistence.csproj" />
    <ProjectReference Include="../OnlyWar.Generation/OnlyWar.Generation.csproj" />
    <Using Include="OnlyWar.Abstractions" />
    <Using Include="OnlyWar.Application.Abstractions" />
    <Using Include="OnlyWar.Application.Battles" />
    <Using Include="OnlyWar.Application.Session" />
    <Using Include="OnlyWar.Application.Storage" />
    <Using Include="OnlyWar.Battles" />
    <Using Include="OnlyWar.Battles.Aftermath" />
    <Using Include="OnlyWar.Battles.Models" />
    <Using Include="OnlyWar.Campaign" />
    <Using Include="OnlyWar.Campaign.Battles.Aftermath" />
    <Using Include="OnlyWar.Campaign.Command" />
    <Using Include="OnlyWar.Campaign.Events" />
    <Using Include="OnlyWar.Campaign.Operations" />
    <Using Include="OnlyWar.Campaign.Fleets" />
    <Using Include="OnlyWar.Campaign.Medical" />
    <Using Include="OnlyWar.Campaign.Recruitment" />
    <Using Include="OnlyWar.Campaign.Settings" />
    <Using Include="OnlyWar.Campaign.Simulation" />
    <Using Include="OnlyWar.Campaign.Strategy" />
    <Using Include="OnlyWar.Campaign.Supply" />
    <Using Include="OnlyWar.Campaign.Turns" />
    <Using Include="OnlyWar.Domain" />
    <Using Include="OnlyWar.Domain.Events" />
    <Using Include="OnlyWar.Domain.Extensions" />
    <Using Include="OnlyWar.Domain.FactionBehaviors" />
    <Using Include="OnlyWar.Domain.Formatting" />
    <Using Include="OnlyWar.Domain.Intelligence" />
    <Using Include="OnlyWar.Domain.Math" />
    <Using Include="OnlyWar.Domain.Missions" />
    <Using Include="OnlyWar.Domain.Orders" />
    <Using Include="OnlyWar.Domain.Planets" />
    <Using Include="OnlyWar.Domain.Recruitment" />
    <Using Include="OnlyWar.Domain.Soldiers" />
    <Using Include="OnlyWar.Domain.Soldiers.Ratings" />
    <Using Include="OnlyWar.Domain.Squads" />
    <Using Include="OnlyWar.Domain.Supply" />
    <Using Include="OnlyWar.Domain.Units" />
    <Using Include="OnlyWar.Medical.Abstractions" />
    <Using Include="OnlyWar.Medical.Readiness" />
    <Using Include="OnlyWar.Medical.Treatment" />
    <Using Include="OnlyWar.Generation.Abstractions" />
    <Using Include="OnlyWar.Generation.World" />
    <Using Include="OnlyWar.Operations.Abstractions" />
    <Using Include="OnlyWar.Operations.Extensions" />
    <Using Include="OnlyWar.Operations.Fleets" />
    <Using Include="OnlyWar.Operations.Intelligence" />
    <Using Include="OnlyWar.Operations.Missions" />
    <Using Include="OnlyWar.Operations.Orders" />
    <Using Include="OnlyWar.Operations.Personnel" />
    <Using Include="OnlyWar.Operations.Planetary" />
    <Using Include="OnlyWar.Operations.Readiness" />
    <Using Include="OnlyWar.Operations.Recruitment" />
    <Using Include="OnlyWar.Operations.StrategicCombat" />
    <Using Include="OnlyWar.Operations.Strategy" />
    <Using Include="OnlyWar.Operations.Turns" />
    <Using Include="OnlyWar.Persistence.Storage" />
    <Using Include="OnlyWar.Runtime.Allocators" />
    <Using Include="OnlyWar.Runtime.Factories" />
    <Using Include="OnlyWar.Runtime.Logging" />
    <Using Include="OnlyWar.Runtime.Random" />
    <Using Include="OnlyWar.Runtime.WorldGeometry" />
    <InternalsVisibleTo Include="OnlyWar.Tests" />
  </ItemGroup>
</Project>
