namespace OnlyWar.Models.Planets
{
    public static class TempPlanetList
    {
        public static string[] PlanetNames = new string[]
        {
            "Abnegat",
            "Absolvia",
            "Acastus Rift",
            "Acheros Vale",
            "Adamance",
            "Adamantis Vigil",
            "Adjuris",
            "Adjutrix Nine",
            "Aedile Prime",
            "Aegis Mourn",
            "Aeonwrack",
            "Aeturnis",
            "Affliction IX",
            "Agonium",
            "Agrarch",
            "Alabast",
            "Alcyor",
            "Alembic Nine",
            "Alkahest",
            "Allegiant Fall",
            "Almsgate",
            "Altarion",
            "Amaranthine Deep",
            "Ambrosine IV",
            "Ammunis",
            "Anchorite's Rest",
            "Anhedron",
            "Ankharite",
            "Annulment",
            "Anointing IX",
            "Anselm's Grave",
            "Antiphon",
            "Apostasy Reach",
            "Apostolic Vale",
            "Aquila Mortis",
            "Aquiline Rest",
            "Arbalest Prime",
            "Arbitrium",
            "Archivault",
            "Ardentis",
            "Ardor Nine",
            "Argent Kell",
            "Armistice Prime",
            "Arraign",
            "Ashen Compact",
            "Ashfall Secundus",
            "Aspera III",
            "Asperity",
            "Assay IX",
            "Asterine",
            "Atonement Deep",
            "Attainder",
            "Attritis",
            "Augurium",
            "Auratine",
            "Aurignac",
            "Austerity Prime",
            "Auterach",
            "Avarice IX",
            "Avenant",
            "Aventine Primus",
            "Avowal",
            "Axehead Nine",
            "Axiom Hollow",
            "Azimuth Vault",
            "Baelgrim",
            "Balefire Deep",
            "Balephor",
            "Ballast IX",
            "Bane's Charity",
            "Bannerfall",
            "Barquentine",
            "Barrow Vex",
            "Basilican Fall",
            "Bastille Nine",
            "Bastion Kelvar",
            "Battlement Prime",
            "Beacon Denied",
            "Beckon's Rest",
            "Bedlam IX",
            "Beggar's Tithe",
            "Bekhaz III",
            "Belfry Prime",
            "Bellamort",
            "Benediction Fall",
            "Beneficia",
            "Bereavement",
            "Bezaleth",
            "Bhaltar VII",
            "Bilgemoor",
            "Bindlestone",
            "Bitter Concord",
            "Blackreef",
            "Blasphemy Rock",
            "Bleakhaven",
            "Blightwarden",
            "Bloodtithe",
            "Bonemarch",
            "Boneyard Prime",
            "Borealis Nine",
            "Brackenspire",
            "Brandsworn",
            "Brazen Anvil",
            "Breakwater IX",
            "Brekkanis",
            "Briarhold",
            "Brigand's Fall",
            "Brimhold",
            "Brimstone Vault",
            "Broken Litany",
            "Brokenwheel",
            "Brumal IX",
            "Brundage IX",
            "Burdenfall",
            "Buttress Nine",
            "Byrsa Minor",
            "Cadaveris",
            "Cadmion",
            "Cairnwatch",
            "Calamity Nine",
            "Caldera Prime",
            "Callowmoor",
            "Calvary Deep",
            "Campanile Prime",
            "Candent VI",
            "Candlewrack",
            "Canonicus",
            "Canticle Prime",
            "Capstone IX",
            "Carceri",
            "Cardinal's Ash",
            "Carnelian Deep",
            "Carrowmoor",
            "Cascade Nine",
            "Casket Nine",
            "Cassivar",
            "Cassock Fall",
            "Castellan's Watch",
            "Catafalque",
            "Catechis",
            "Caul Prime",
            "Cauldris",
            "Celadine",
            "Cenotaph IX",
            "Censura",
            "Cerberan Gate",
            "Cerement",
            "Chainbreak",
            "Chalice Nine",
            "Chancel Prime",
            "Chantry Fall",
            "Charnelspire",
            "Chastise Nine",
            "Cherubim Fall",
            "Chimerine",
            "Cindergarde",
            "Cinderwake",
            "Cistern Nine",
            "Citadel Vorn",
            "Clarion Rest",
            "Clarity Denied",
            "Cleaverock",
            "Clovenhold",
            "Coalgrave",
            "Codicil Prime",
            "Coffer IX",
            "Cogitus Ultima",
            "Cognomen",
            "Colossae Prime",
            "Colwyn's Reach",
            "Commutation",
            "Compliance 88",
            "Concordant Ash",
            "Confessor's Rest",
            "Conflagris",
            "Conquest Denied",
            "Consecrate IX",
            "Constancy Prime",
            "Contrition",
            "Convocant",
            "Copperfall",
            "Cordwain",
            "Cornerstone IX",
            "Corrigan's Hope",
            "Corundum Prime",
            "Corvane II",
            "Covenant Ash",
            "Cravenhold",
            "Credence Nine",
            "Cremain Prime",
            "Crimson Tithe",
            "Crookback",
            "Crownfall",
            "Crozier's Landing",
            "Crucible Deep",
            "Cryptheim",
            "Cudgel Nine",
            "Culpar Prime",
            "Curfew IX",
            "Cuspis Alpha",
            "Cynosure",
            "Cyrilline",
            "Dacharon",
            "Daggerfell",
            "Dagmar's Rest",
            "Dalmatis",
            "Damaskene",
            "Damnation Gate",
            "Darkling Vault",
            "Dauntless Hold",
            "Dauphine IX",
            "Dawnless",
            "Deacon's Fall",
            "Deadlight",
            "Dearth Prime",
            "Debtor's Rock",
            "Decanate",
            "Decimus Vale",
            "Declension IX",
            "Defilade Nine",
            "Deiphage",
            "Delict Prime",
            "Delverath",
            "Demarch",
            "Demesne IX",
            "Denunciation",
            "Deodand",
            "Depredon",
            "Derelict IX",
            "Deshkar IV",
            "Desiccar",
            "Despoil Nine",
            "Detritan Prime",
            "Devotional IX",
            "Devout's Ash",
            "Dholveth",
            "Dhoram Fell",
            "Diadem Nine",
            "Dictamen",
            "Diligent Fall",
            "Dimlight IX",
            "Diocesan Prime",
            "Direwatch",
            "Dirge",
            "Disavowal",
            "Discord Nine",
            "Dismal Rock",
            "Dissent IX",
            "Dolmenfast",
            "Dolorous Prime",
            "Dominion Ash",
            "Dominis Rex",
            "Doomsayer's Rest",
            "Dourmarch",
            "Dowager's Fall",
            "Draconis Vault",
            "Drakemoor",
            "Dreadwake",
            "Dregmoor",
            "Drossvane",
            "Drownfast",
            "Drudgemarch",
            "Dryhollow",
            "Duennos",
            "Dulcimer VII",
            "Dunnage IX",
            "Durance Vile",
            "Dusklight Prime",
            "Dustbind",
            "Dyerswatch",
            "Ebonhold",
            "Ecclesian Reach",
            "Echelon IX",
            "Edifice Prime",
            "Effacement",
            "Effigy",
            "Egress Nine",
            "Eiderhold",
            "Elderfast",
            "Elegiac Deep",
            "Elegy",
            "Ellisandra",
            "Embargo IX",
            "Emberdrift",
            "Emberwatch",
            "Emendation",
            "Emissary's Fall",
            "Enclave Nine",
            "Endowment Prime",
            "Enfilade IX",
            "Engram Vault",
            "Enkilith",
            "Enmity Prime",
            "Ensign's Rest",
            "Entreaty Nine",
            "Envoi",
            "Ephorate",
            "Epitaphon",
            "Equerry IX",
            "Equinal V",
            "Erasure Deep",
            "Erminault",
            "Errant's Fall",
            "Escheat Prime",
            "Esperandum",
            "Estovar",
            "Ethelbern",
            "Evensong IX",
            "Eventide",
            "Exactor Prime",
            "Excise Nine",
            "Exequy Prime",
            "Exhortis",
            "Exile's Anvil",
            "Expiation",
            "Exsultis Nova",
            "Extremis Vault",
            "Eyeless Deep",
            "Faldriac",
            "Fallowmoor",
            "Falsehood IX",
            "Famine's Table",
            "Fanewrack",
            "Farrowgate",
            "Farthing Nine",
            "Fastness IX",
            "Fathomless Deep",
            "Fealty Prime",
            "Feldspar IX",
            "Fellhaven",
            "Fennimore's Rest",
            "Ferrous Gate",
            "Ferrum Quintus",
            "Fetterfall",
            "Feverwatch",
            "Fidelis Umbra",
            "Fiefdom IX",
            "Filigran Prime",
            "Finality",
            "Firebrand Deep",
            "Firmament",
            "Fissurehold",
            "Flagellant's Rest",
            "Flenswick",
            "Flintmarch",
            "Floodmoor",
            "Fogbound IX",
            "Foliot Nine",
            "Fontaine's Fall",
            "Forbearance",
            "Fordwrack",
            "Foresworn Prime",
            "Forgiveness Denied",
            "Forlorn Concord",
            "Formalis",
            "Fortitude IX",
            "Fosswater Prime",
            "Foundling's Rest",
            "Fount of Ash",
            "Fracture Nine",
            "Franklin's Toil",
            "Fraywater",
            "Freehold IX",
            "Fretmarch",
            "Frigus Prime",
            "Frostgale IX",
            "Frostmarrow",
            "Fugue Deep",
            "Fulcrum Nine",
            "Fulminarch",
            "Furnace Gate",
            "Furrowfast",
            "Fusilade Prime",
            "Gabion IX",
            "Galehold",
            "Gallantine",
            "Gallowsreach",
            "Gambit Tertius",
            "Ganthar",
            "Gantryfall",
            "Garethis IV",
            "Garrock Prime",
            "Gaudium IX",
            "Gaunt Hollow",
            "Gavelkind",
            "Gearfast",
            "Geldwater",
            "Gemwrack Nine",
            "Gentian Fall",
            "Gethsemal",
            "Ghastrek",
            "Gholvan",
            "Ghostmarch",
            "Gibbet Rock",
            "Gildvane",
            "Girdlestone",
            "Glaciem Prime",
            "Glaivemoor",
            "Gleanfall",
            "Gloamfast",
            "Gloomwatch",
            "Gnarlhold",
            "Goadmoor",
            "Godless Reach",
            "Gorget Nine",
            "Gorlock Prime",
            "Gospelrock",
            "Governance IX",
            "Grailwatch",
            "Granary Prime",
            "Grapnel Nine",
            "Gratitude Denied",
            "Gravamen",
            "Gravecant",
            "Greyfast",
            "Grievance IX",
            "Grim Ordinal",
            "Grindstone Prime",
            "Grist Nine",
            "Grotesk Prime",
            "Groundswell IX",
            "Grudgehold",
            "Guerdon Prime",
            "Guilder's Rest",
            "Gullwatch",
            "Gunwale IX",
            "Gyrfalcon Deep",
            "Gyveshold",
            "Hackleford",
            "Hadrasin",
            "Haggard's Rest",
            "Hailstone Prime",
            "Halberd Nine",
            "Halcyon Ruin",
            "Hallowmark",
            "Halterfast",
            "Hammerfall",
            "Handfast IX",
            "Hangman's Vigil",
            "Hardship Prime",
            "Harken Deep",
            "Harrowvane",
            "Haspar IX",
            "Hatchetfall",
            "Haulfast",
            "Havenless",
            "Hazelmoor",
            "Headstone Prime",
            "Hearthfall",
            "Heartsblood Deep",
            "Heathenfall",
            "Hecatane",
            "Hecklestone",
            "Hedgerow Prime",
            "Heirloom IX",
            "Hellebore Deep",
            "Helmsgate",
            "Hemlock Prime",
            "Henchmoor",
            "Heraldfall",
            "Heresiarch's Tomb",
            "Hermitage IX",
            "Hessian Rock",
            "Hexengrad",
            "Hierophant Prime",
            "Highgibbet",
            "Hinderfast",
            "Hoarfrost IX",
            "Hobwater",
            "Hollowbone",
            "Hollowmoor",
            "Homily Prime",
            "Hopewell IX",
            "Hornfast",
            "Hoshek Prime",
            "Hospitaler's Rest",
            "Hostillian",
            "Housecarl's Rest",
            "Howlgrave",
            "Huckster's Fall",
            "Hulderin",
            "Humility Prime",
            "Hungerfall",
            "Huskvane",
            "Hyaline Deep",
            "Hymnus Secundus",
            "Hyrmadan",
            "Iconoclast Deep",
            "Idolatry Rock",
            "Ignifer",
            "Ignomen",
            "Illumine Nine",
            "Immolus",
            "Immure Nine",
            "Impasse IX",
            "Imperitus Vale",
            "Impiety Deep",
            "Imprecation",
            "Incense Fall",
            "Incunabula",
            "Indenture",
            "Indict Nine",
            "Infernus Gate",
            "Ingot Prime",
            "Ingram's Toil",
            "Inheritance Denied",
            "Iniquity Deep",
            "Injunction IX",
            "Inkwater",
            "Inquest",
            "Inscrutis",
            "Insurgis",
            "Intaglio Prime",
            "Intercession IX",
            "Interdict IX",
            "Intonement",
            "Invective Nine",
            "Inviolate Prime",
            "Iron Repose",
            "Ironmourn",
            "Ironwake",
            "Irrigar Prime",
            "Isenvault",
            "Isolate IX",
            "Ithrandel",
            "Ivorygate",
            "Jackal's Wake",
            "Jackstraw Nine",
            "Jagworth",
            "Janissar Prime",
            "Jarnhold",
            "Jerichane",
            "Jetsam IX",
            "Jezail Prime",
            "Jinxwater",
            "Jorvath",
            "Jotunhelm",
            "Jubilee Rock",
            "Judicant",
            "Junction Nine",
            "Juniper Fall",
            "Junker's Verge",
            "Justiciar's Ash",
            "Kaerdruth",
            "Kaftar Prime",
            "Kalderash",
            "Kalvex Prime",
            "Kanterbrec",
            "Karrowmund",
            "Karvenna",
            "Kastellan Nine",
            "Kastrigan",
            "Kaverin",
            "Kaz'ghul",
            "Keelhaul Deep",
            "Kelvarn",
            "Kelvinar",
            "Kenning Nine",
            "Kernsworth",
            "Kestrelfall",
            "Kettlebridge",
            "Keystone Prime",
            "Khaldrach",
            "Khalfast",
            "Kharsivane",
            "Khem-Ur",
            "Kholvath",
            "Kiltrek",
            "Kindlerift",
            "Kindred Fall",
            "Kinsmoor",
            "Kirensk",
            "Kirkfell",
            "Kismet IX",
            "Klavendorn",
            "Klaviar",
            "Knellwater",
            "Knollhaven",
            "Kohlvast",
            "Konstrad",
            "Korvath IV",
            "Kraskan",
            "Kraveller",
            "Krellmoor",
            "Krenshaw IX",
            "Krimsvale",
            "Krossgate",
            "Kruvien",
            "Kulmar Prime",
            "Kyrant Prime",
            "Kyriemund",
            "Labarum Prime",
            "Lachrymae",
            "Lacquerfall",
            "Ladensworn",
            "Lament XII",
            "Lamplight IX",
            "Lanceward",
            "Landfall Prime",
            "Langstone IX",
            "Lanternwrack",
            "Lapidary Nine",
            "Larchmoor",
            "Lastrock",
            "Lastwater",
            "Latter Vigil",
            "Lattermarch",
            "Laudation Nine",
            "Lavelock Prime",
            "Lawgiver's Rest",
            "Leadenfall",
            "Leaguer Nine",
            "Leechwater",
            "Legacy Denied",
            "Legatine",
            "Lenity Prime",
            "Lepridus",
            "Lessertide",
            "Lethbridge Reach",
            "Levantis",
            "Levinbolt Deep",
            "Lex Nomine",
            "Libation IX",
            "Liburnia",
            "Lichgate",
            "Liegefall",
            "Lightless Prime",
            "Linchpin IX",
            "Lindworm Nine",
            "Litanus",
            "Litharge Prime",
            "Loamfast",
            "Lockstep Nine",
            "Lodemark Prime",
            "Lodestone Prime",
            "Lohanmar",
            "Longshadow Deep",
            "Longwinter",
            "Lorevault",
            "Losswater",
            "Lowmarch",
            "Loyalty Denied",
            "Lucent Fall",
            "Lucre's Fall",
            "Lumen Prime",
            "Lustration IX",
            "Lykandra",
            "Lyrian Deep",
            "Macerine Prime",
            "Machavel",
            "Maddox IX",
            "Madrigal Rift",
            "Magistrate Fall",
            "Maidenfast",
            "Malachyr Deep",
            "Malgareth",
            "Mallowmoor",
            "Malvern IX",
            "Mandate Prime",
            "Mandible",
            "Manifest Nine",
            "Mantlefall",
            "Marchwarden",
            "Margrave Deep",
            "Marlinspike Prime",
            "Marrowgast",
            "Marshal's Ash",
            "Martyr's Ledger",
            "Maskavan",
            "Masquer Nine",
            "Mattock Prime",
            "Maulstone IX",
            "Mausolan Prime",
            "Maverick's Rest",
            "Mawgate",
            "Meadowfast",
            "Meldrith",
            "Memento Prime",
            "Mendacity IX",
            "Mendicant",
            "Merchant's Toll",
            "Mercy Denied",
            "Meritas",
            "Mesnegar",
            "Mesophane",
            "Mettlefast",
            "Middenhall",
            "Midwinter Prime",
            "Milestone IX",
            "Millwright's Rest",
            "Minaret Nine",
            "Mirefast",
            "Miserere",
            "Misericord Deep",
            "Misrule Prime",
            "Mistvault Nine",
            "Mithergast",
            "Mnemos Prime",
            "Moatfall",
            "Moldergrave",
            "Molvenar",
            "Monition",
            "Monkshood Prime",
            "Monody Prime",
            "Moonless IX",
            "Moorwrack",
            "Morbidus Rex",
            "Morrowfell",
            "Mortmain",
            "Mosswater",
            "Mothgate",
            "Mourncastle",
            "Mudlark's Rest",
            "Mullhaven",
            "Munsgrave",
            "Muntridge",
            "Muster Nine",
            "Mutinous Rock",
            "Myrrhac",
            "Myrtlefall",
            "Nacreous Deep",
            "Nadirine",
            "Namesake Nine",
            "Narthex Prime",
            "Nascence Prime",
            "Naxaran",
            "Nazrilek",
            "Nebbanock",
            "Necrofane",
            "Needlefast",
            "Nefrit Prime",
            "Negation IX",
            "Nemetch",
            "Nemethon",
            "Nepenthe Deep",
            "Nephilax",
            "Nettlemoor",
            "Nevermourn",
            "Newgallows",
            "Nightpyre Prime",
            "Nilvarr Gate",
            "Nimbus Fall",
            "Nithing Prime",
            "Noctivar",
            "Nomarch Nine",
            "Nomen Sacrum",
            "Nonesuch Prime",
            "Northwatch IX",
            "Nostrum Deep",
            "Notary's Fall",
            "Novena Secundus",
            "Novitiate Prime",
            "Noxwater",
            "Nullhaven",
            "Numbstone Prime",
            "Nuncio Nine",
            "Nyssander",
            "Nyxandros",
            "Oathfall",
            "Obelis IX",
            "Oblate Prime",
            "Obloquy",
            "Occlusion IX",
            "Occultis Prime",
            "Ochremoor",
            "Odessine",
            "Offertory",
            "Officium Nine",
            "Omission Deep",
            "Ommadar",
            "Onerous Vale",
            "Ordolith",
            "Orisonfall",
            "Ossuar",
            "Ostervant",
            "Ostracon IX",
            "Ouroboran",
            "Pactstone Prime",
            "Pallbearer's Rest",
            "Pallidus IV",
            "Palsgrave",
            "Panopt",
            "Pardoner's Fall",
            "Parvenal",
            "Patrimony Deep",
            "Pauper's Crown",
            "Penitence Deep",
            "Pennant Prime",
            "Perdurance",
            "Perjury Rock",
            "Pestilar",
            "Petraeon VII",
            "Petrichor Deep",
            "Phaerix",
            "Pikewatch",
            "Pillar of Salt",
            "Pinionfall",
            "Plainsong Prime",
            "Polaris Vane",
            "Poniard Prime",
            "Portentum",
            "Praxis Ultima",
            "Prefectus Nine",
            "Primogen",
            "Proscript",
            "Psalmis",
            "Pyreholt",
            "Pyrewind",
            "Pyroclast Nine",
            "Quagfast",
            "Quarantine 12",
            "Quellmoor",
            "Querent Prime",
            "Querulus",
            "Quicklime Deep",
            "Quiescence",
            "Quietus Vault",
            "Quillhaven",
            "Quorum Prime",
            "Rabblefast",
            "Rackenmoor",
            "Ragged Faith",
            "Rampart IX",
            "Rancour Deep",
            "Ransom's Deep",
            "Ravelin Prime",
            "Ravenmark",
            "Recidivus",
            "Recusant Fall",
            "Redgrave Fall",
            "Redoubt Prime",
            "Reeve's Rest",
            "Regicide Prime",
            "Reliquar",
            "Remittance Deep",
            "Remnant Vale",
            "Reprisal Rock",
            "Requiem Nine",
            "Retribution's Ash",
            "Rhoskvar",
            "Riftwarden",
            "Rimebound",
            "Rivenmoor",
            "Rookery Prime",
            "Rothgar's Hope",
            "Ruinatus",
            "Rustgrave",
            "Sablewrack",
            "Sackcloth Prime",
            "Sacrament VII",
            "Saltmourn",
            "Salvor's Rest",
            "Sanctimony Deep",
            "Sanguis Vale",
            "Sarcophus Prime",
            "Sawtooth IX",
            "Scabbardfall",
            "Scaffold Nine",
            "Scarlet Vigil",
            "Sconce Prime",
            "Scourgehold",
            "Scriptorum IX",
            "Scrivener's Rest",
            "Scythemoor",
            "Sedgewater",
            "Sedition Nine",
            "Selvage Nine",
            "Sepulchris",
            "Seraphage",
            "Servitude IV",
            "Sextant Prime",
            "Shackle Reach",
            "Shroudmoor",
            "Sibylline",
            "Sigilis",
            "Silentine",
            "Skarn Vothis",
            "Slagmoor",
            "Solace Denied",
            "Somnifer Deep",
            "Sorrowmark",
            "Spearpoint IX",
            "Stagnis",
            "Stormbreak Prime",
            "Stricture",
            "Suffragis",
            "Sundermoor",
            "Supplicant's Fall",
            "Sylvantis",
            "Tabulus Rex",
            "Tallowfast",
            "Talonspire",
            "Tanner's Rest",
            "Tarnhast",
            "Temerity Deep",
            "Tenebris Ultima",
            "Tessellar",
            "Thanadrix",
            "Thaneshold",
            "Theodicy",
            "Thornvale",
            "Threshfall",
            "Thurible Prime",
            "Tillage IX",
            "Tinderwake",
            "Tithe's End",
            "Tollgate Nine",
            "Torment IX",
            "Tournais VII",
            "Trestlemarch",
            "Tribute Nine",
            "Trucidus",
            "Truncheon IX",
            "Tumultis",
            "Turgast Deep",
            "Tyburn's Gate",
            "Ulvenhold",
            "Umberfast",
            "Umbrant",
            "Unbidden Deep",
            "Unction",
            "Undercroft",
            "Undertow Nine",
            "Unhallow",
            "Unquiet Vault",
            "Upsilon Kravn",
            "Urgath Prime",
            "Usher's Fall",
            "Usurine",
            "Utmark",
            "Vagabond Rock",
            "Vagrant's Cross",
            "Valediction",
            "Valiance IX",
            "Vanguard Rest",
            "Varkoth",
            "Vaultstone",
            "Veilbreak",
            "Vellumgate",
            "Venatrix",
            "Venturer's Rest",
            "Verdict Prime",
            "Verglas Prime",
            "Vespertine",
            "Vestibule Nine",
            "Vetchmoor",
            "Vexillar",
            "Viaticum",
            "Vigilant Ash",
            "Vindicta",
            "Vitrean",
            "Voidmarch",
            "Votary Prime",
            "Vowfast",
            "Vulgrath",
            "Vyrmount",
            "Wailing Deep",
            "Wanewater",
            "Wardenspire",
            "Warrant IX",
            "Warrenfast",
            "Watchfire",
            "Weeping Reach",
            "Weftmoor",
            "Whetstone Prime",
            "Whittlegate",
            "Widow's Verge",
            "Windlass IX",
            "Winnowhold",
            "Woadfall",
            "Wretch's Gate",
            "Wyrmgate",
            "Xalgoth",
            "Xantheum",
            "Xenobane Prime",
            "Xerath IX",
            "Xerophane",
            "Xibarrus",
            "Xolmec",
            "Xothgar",
            "Yaldabar",
            "Yardarm Nine",
            "Yarkosh",
            "Yeldrith",
            "Yewgate",
            "Ymirvast",
            "Yorrick's Fall",
            "Ythrangar",
            "Zabrathis",
            "Zealot's Rest",
            "Zenithine",
            "Zephrandis",
            "Zetacor Prime",
            "Zharkovan",
            "Zilaskar",
            "Zoltheris",
            "Zorrimund",
            "Zuldrach",
            "Zunderhold",
            "Zyphara"
        };
    }
}
