<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>OnlyWar</RootNamespace>
  </PropertyGroup>
  <ItemGroup>

    <InternalsVisibleTo Include="OnlyWar.Tests" />
    <InternalsVisibleTo Include="OnlyWar.HeadlessTests" />
  </ItemGroup>
</Project>
