<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>OnlyWar</RootNamespace>
  </PropertyGroup>
  <ItemGroup>

    <ProjectReference Include="../OnlyWar.Abstractions/OnlyWar.Abstractions.csproj" />

    <InternalsVisibleTo Include="OnlyWar.Tests" />
  </ItemGroup>
</Project>
